import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Nav from "./(landing)/nav";
import Footer from "./(landing)/footer";

export const ROBOTO_DEFAULT = Roboto({
  subsets: ["latin"],
  weight: "300",
  variable: "--font-roboto-default"
})

export const ROBOTO_TITLE = Roboto({ 
  subsets: ["latin"], 
  weight: "100",
  variable: "--font-roboto-title"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ROBOTO_DEFAULT.className} ${ROBOTO_DEFAULT.variable} ${ROBOTO_TITLE.variable}`}>
        <div>{children}</div>
      </body>
    </html>
  );
}
